### ISSUE TITLE
Issue in Groups & Refugees

### ISSUE THREAD

**Issue by lenAchi** [Lassulus/refugeerouter#27]
Issue: adding new Group requires to add a refugee as contact partner, if refugee is not available, adding a new refugee is possible, but this requires to specify this refugee to a group, but here the group is not saved and cannot be selected 
Both seems mutually dependent.
--> turning in circle :)
Target description: creating a group does NOT require to select a refugee as contact person

**Comment by Lassulus** [comment]
yes, thats indeed a limitation of the current data model. right now the contact person should be optional so it is possible to create the group first. then a refugee and then edit the group to set the contact. The complexity of the group/refugee relationship is the primary reason we want to use custom views to handle that part and not the admin interface
